### ISSUE TITLE
Null check

### ISSUE THREAD

**Issue by aBuder** [jicang/healywatch_reactive#46]
```log
flutter: Null check operator used on a null value
flutter: 
#0      SharedPrefUtils.getBool (package:healy_watch_sdk/util/shared_pref.dart:61:14)
#1      SharedPrefUtils.isFirmware (package:healy_watch_sdk/util/shared_pref.dart:42:12)
#2      new BluetoothConnectionUtil.<anonymous closure> (package:healy_watch_sdk/util/bluetooth_conection_util.dart:76:52)
#3      new BluetoothConnectionUtil.<anonymous closure> (package:healy_watch_sdk/util/bluetooth_conection_util.dart:71:36)
#4      _rootRunUnary (dart:async/zone.dart:1436:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#11     _rootRun (dart:async/zone.dart:1420:47)
#12     _CustomZone.run (dart:async/zone.dart:1328:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#15     _rootRun (dart:async/zone.dart:1428:13)
#16     _CustomZone.run (dart:async/zone.dart:1328:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
flutter: ----------------------------------------------------

```

**Comment by jicang** [comment]
已修改
