### ISSUE TITLE
LateInitializationError: Field 'isConnect' has not been initialized.

### ISSUE THREAD

**Issue by aBuder** [jicang/healywatch_reactive#47]
```log
flutter: LateInitializationError: Field 'isConnect' has not been initialized.
[log] [JOB]c051901fda048badda0aed8e4bdbb3d2:triggered by timer_trigger
flutter: 
#0      BluetoothConnectionUtil.isConnect (package:healy_watch_sdk/util/bluetooth_conection_util.dart)
#1      BluetoothConnectionUtil.isConnected (package:healy_watch_sdk/util/bluetooth_conection_util.dart:394:12)
#2      HealyWatchSDKImplementation.isConnected (package:healy_watch_sdk/healy_watch_sdk_impl.dart:85:26)
#3      FirmwareUpdateCubit._connectToDevice (package:healyWatchApp/common/cubits/firmware_update/firmware_update_cubit.dart:46:26)
#4      FirmwareUpdateCubit.checkFirmware (package:healyWatchApp/common/cubits/firmware_update/firmware_update_cubit.dart:28:16)
#5      MyApp.build.<anonymous closure>.<anonymous closure> (package:healyWatchApp/main.dart:461:20)
#6      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:727:36)
#7      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:583:33)
#8      Provider.of (package:provider/src/provider.dart:305:37)
#9      ReadContext.read (package:provider/src/provider.dart:658:21)
#10     _BlocBuilderBaseState.initState (package:flutter_bloc/src/bloc_builder.dart:129:36)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4805:57)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#47     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1242:37)
#48     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1227:20)
#49     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573:19)
#50     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1220:12)
#51     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#52     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1968:59)
#53     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:916:15)
#54     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1968:14)
#55     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#56     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
#57     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239:19)
#58     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282:12)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#60     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#61     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#63     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#64     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#65     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#79     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#81     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#82     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#83     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#87     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#88     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#89     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#90     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#95     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#101    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:240:19)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#103    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#104    _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#106    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#107    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#108    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#112    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#113    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#116    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#118    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#120    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#121    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#122    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#123    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#124    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#125    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#126    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#128    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#130    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#133    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#134    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#135    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#137    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#138    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#139    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#140    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#141    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#142    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#143    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#144    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#145    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#146    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#147    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#148    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#149    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#150    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#151    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#152    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#153    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#154    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3420:14)
#155    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#156    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#157    RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#158    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:745:15)
#159    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#160    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#161    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#162    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#163    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#164    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#165    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#166    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#167    _rootRun (dart:async/zone.dart:1428:13)
#168    _CustomZone.run (dart:async/zone.dart:1328:19)
#169    _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#170    _invoke (dart:ui/hooks.dart:166:10)
#171    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#172    _drawFrame (dart:ui/hooks.dart:129:31)

```

**Comment by jicang** [comment]
已经解决
