### ISSUE TITLE
Exception while enter exercise

### ISSUE THREAD

**Issue by aBuder** [jicang/healywatch_reactive#9]
While enter an exercise, we got an error.

```log
I/flutter (14186): notifyData 18 00 00 00 00 00 00 00 00 00 0b 00 00 00 00 00 00 00 00 23 
E/flutter (14186): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'countdownTimer' has not been initialized.
E/flutter (14186): #0      ExercisePageState.countdownTimer (package:healywatch_reactive/activity/ExercisePage.dart)
E/flutter (14186): #1      ExercisePageState.startTimer (package:healywatch_reactive/activity/ExercisePage.dart:181:9)
E/flutter (14186): #2      ExercisePageState.showExerciseData.<anonymous closure> (package:healywatch_reactive/activity/ExercisePage.dart:157:9)
E/flutter (14186): #3      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (14186): #4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (14186): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (14186): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (14186): #7      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (14186): #8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (14186): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (14186): #10     _rootRun (dart:async/zone.dart:1420:47)
E/flutter (14186): #11     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (14186): #12     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (14186): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (14186): #14     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (14186): #15     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (14186): #16     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (14186): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (14186): #18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14186): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (14186): 
I/flutter (14186): notifyData 18 00 00 00 00 00 00 00 00 00 0b 00 00 00 00 00 00 00 00 23 
E/flutter (14186): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'countdownTimer' has not been initialized.
```

**Comment by jicang** [comment]
v1.1已经更新

**Comment by aBuder** [comment]
LGTM
